# Generated by Django 4.1.2 on 2022-10-13 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=13)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.JSONField()),
                ('publisher', models.CharField(max_length=256)),
                ('published_data', models.SmallIntegerField()),
                ('page_count', models.SmallIntegerField()),
                ('categories', models.JSONField()),
                ('image_links', models.JSONField()),
                ('language', models.CharField(max_length=10)),
                ('preview_link', models.CharField(max_length=512)),
                ('info_link', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_books', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
